### ISSUE TITLE
`ActivityStartDate` filiter not working in ds_observations(), Error 400: Bad Request

### ISSUE THREAD

**Issue by p-schaefer** [gordonfn/datastreamr#9]
The example from the help file produces an error:

```r
datastreamr::ds_observations(
                            api_token=key,
                            select=c("ResultValue"), 
                            filter=c("CharacteristicName = pH","ActivityStartDate>2019-01-01"),
                            top=1000
                           )
```
`Error in check_status(response$status_code) : 
  400: Bad Request. Please ensure that proper filters and selects are being passed`

**Comment by willfarrell** [comment]
I'm not sure what the r package does behind the scenes, but the API uses OData which needs string values to be quoted and uses operators like `eq` and `gt`. I the README is think `"CharacteristicName=Dissolved oxygen saturation"` contains an error.

https://github.com/datastreamapp/api-docs?tab=readme-ov-file#url-parameters

**Comment by p-schaefer** [comment]
Sorry, I wasn't clear. It is the `ActivityStartDate` filter that's causing the problem (though I agree, `CharacteristicName` should be quoted, but because there is no spaces or special characters in 'pH', I think it works). Removing the `ActivityStartDate` filter does allow the above code to run. The R package does translate the operators: https://github.com/datastreamapp/datastreamr/blob/4eea6215e9c0959988b7bb3fa557abc7553e63eb/R/datastreamr.R#L294-L299

I've tried quoting the date, and that didn't work either. Is the date operator different from other operators?

**Comment by meghanDS** [comment]
It's been a second since I've used any date filtering in the API, but I wanted to jump in and try. I get the same thing as Patrick. I also tried this in python @willfarrell 

```
results = list(observations({
    '$select': 'ResultValue',
    '$filter': "CharacteristicName eq 'pH' and ActivityStartDate gt '2019-01-01'"
}))
```

with the same 400 issue - anything obviously incorrect with my syntax here?

**Comment by lorilogan** [comment]
Closing this one as resolved...
Essentially `ActivityStartDate` was deprecated and replaced with `ActivityStartYear`
- R package documentation needs to be updated
   - Specifically some examples require update
- List of allowed values in the R package should be removed so there is 1 source to update i.e. the main page for allowed values (as per other packages)

@meghanDS I will make a ticket from this comment to track those tasks.
